image: python:3.8.10

stages:
  - Linux
  - Heroku

deploy-on-Linux:
  stage: Linux

  script:
    - apt-get install -y python-dev python-pip
    - vagrant up
    - vagrant ssh
    - FLASK_APP=crypto_homepage.py
    - pip install -r requirements.txt

deploy-on-Heroku:
  stage: Heroku

  script:
    - Heroku
