# main 브랜치에 push가 들어올 때 동작하는 job
deploy:
  only:
    - main
  before_script:
    - "source /venv/bin/activate"
    - "pip install -r requirements.txt"
    - "pip flask db init"
    - "pip flask db migrate"
    - "pip flask db upgrade"

  script:
    - "flask run"
